import '@styles/globals.css'
import { ReactNode } from 'react'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface Props {
  children: ReactNode;
}

const RootLayout: React.FC<Props> = ({ children }) => (
  <html lang='en'>
    <body suppressHydrationWarning={true} >
        {children}
    </body>
  </html>
);

export default RootLayout;