import '../styles/globals.css'
import Head from 'next/head'
import Pages from '../pages.json'
import Navbar from '../components/header/navbar'
import Social from '../components/social'
import Social_media from '../social_media.json'
import Footer from '../components/footer/footer'
import { useState } from 'react'

function MyApp({ Component, pageProps }) {
  const [user, setUser] = useState({value: null})
  const [key, setKey] = useState(0)
  if (typeof window !== 'undefined'){
    const token = localStorage.getItem(token)
    if (token){
      setUser({value: token})
      setKey(Math.random())
    }
  }

  return <>
    <div>
      <Head>
        <title>RCSC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo/rcsc-logo.png" />
      </Head>
      <Navbar props={Pages} key={key} user={user}/>
      <Component {...pageProps} />
      <Social props = {Social_media}/>
      <Footer />
    </div>
  </>
}

export default MyApp
