import Head from 'next/head'
import Navbar from '../components/navbar'

export default function Home() {
  return (
    <div className='container'>
      <Head>
        <title>RCSC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/rcsc-logo.ico" />
      </Head>
      <Navbar></Navbar>
    </div>
  )
}
