import Head from 'next/head'
import Header from '../components/header/header'

export default function Home() {
  return (
    <div className='container'>
      <Head>
        <title>RCSC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo/rcsc-logo.png" />
      </Head>
      <Header />
    </div>
  )
}
